<?php

/**
 * Implements hook_ctools_plugin_directory().
 */
function addressfield_es_ctools_plugin_directory($module, $plugin) {
  if ($module == 'addressfield') {
    return 'plugins/' . $plugin;
  }
}

function addressfield_es_form_views_exposed_form_alter(&$form, $form_state){
  if ($form['#id'] == 'views-exposed-form-mapa-de-centros-page-1'){
    dsm($form);
    $form['provincia'] = array (
      '#type' => 'select',
      '#options' => array(
        ''   => t('Todas'),
        'C' => t('A Coruña'),
        'VI' => t('Álava'),
        'AB' => t('Albacete'),
        'A' => t('Alicante'),
        'AL' => t('Almería'),
        'O' => t('Asturias'),
        'AV' => t('Ávila'),
        'BA' => t('Badajoz'),
        'PM' => t('Baleares'),
        'B' => t('Barcelona'),
        'BU' => t('Burgos'),
        'CC' => t('Cáceres'),
        'CA' => t('Cádiz'),
        'S' => t('Cantabria'),
        'CS' => t('Castellón'),
        'CE' => t('Ceuta'),
        'CR' => t('Ciudad Real'),
        'CO' => t('Córdoba'),
        'CU' => t('Cuenca'),
        'GI' => t('Girona'),
        'GR' => t('Granada'),
        'GU' => t('Guadalajara'),
        'SS' => t('Guipúzcoa'),
        'H' => t('Huelva'),
        'HU' => t('Huesca'),
        'J' => t('Jaén'),
        'LO' => t('La Rioja'),
        'GC' => t('Las Palmas'),
        'LE' => t('León'),
        'L' => t('Lleida'),
        'LU' => t('Lugo'),
        'M' => t('Madrid'),
        'MA' => t('Málaga'),
        'ML' => t('Melilla'),
        'MU' => t('Murcia'),
        'NA' => t('Navarra'),
        'OR' => t('Ourense'),
        'P' => t('Palencia'),
        'PO' => t('Pontevedra'),
        'SA' => t('Salamanca'),
        'SF' => t('Santa Cruz de Tenerife'),
        'SG' => t('Segovia'),
        'SE' => t('Sevilla'),
        'SO' => t('Soria'),
        'T' => t('Tarragona'),
        'TE' => t('Teruel'),
        'TO' => t('Toledo'),
        'V' => t('Valencia'),
        'VA' => t('Valladolid'),
        'BI' => t('Vizcaya'),
        'ZA' => t('Zamora'),
        'Z' => t('Zaragoza'),
      ),
      '#default_value' => '',
    );
  }	
}
